Resources:
  ContactsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.environment.CONTACTS_TABLE}
      AttributeDefinitions:
        - AttributeName: contactId
          AttributeType: S
      KeySchema:
        - AttributeName: contactId
          KeyType: HASH
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST

  MessagesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.environment.MESSAGES_TABLE}
      AttributeDefinitions:
        - AttributeName: messageId
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
        - AttributeName: contactId
          AttributeType: S
      KeySchema:
        - AttributeName: messageId
          KeyType: HASH
        - AttributeName: createdAt
          KeyType: RANGE
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: ${self:provider.environment.CONTACT_ID_INDEX}
          KeySchema:
            - AttributeName: contactId
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL # What attributes will be copied to an index
      